apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.fullname" . }}-config
data:
  database_url: {{ .Values.database.url | quote }}
  port: {{ .Values.database.port | quote }}
  log_level: "info"